#server:
#  port: 8001
#spring:
#  application:
#    name: microservice-eureka
#eureka:
#  instance:
#    hostname: localhost #eureka服务端实例名称
#  client:
#    register-with-eureka: false #false表示不向注册中心注册自己
#    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务
#  server:
#    enable-self-preservation: false #禁用自我保护模式


#以上是单机模式
#以下是集群模式

server:
  port: 8001  #服务端口号
eureka:
  client:
    service-url:
      #相互注册，组成一个集群，实现高可用
      defaultZone: http://eureka8002:8002/eureka/,http://eureka8003:8003/eureka/
  instance:
    #主机名
    hostname: eureka8001
spring:
  application:
    #服务名称
    name: eureka-availability-server