
server:
  port: 8761  #服务端口号
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #主机名
    hostname: localhost
spring:
  application:
    #服务名称
    name: eureka-availability-server-8761
